import { CategoryInfo, Performer, Video } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'trending',
    name: 'Trending',
    icon: 'local_fire_department',
    heroImage: '/images/categories/trending.jpg',
    description: 'The hottest and most popular exclusive content trending across FapXX.'
  },
  {
    id: 'amateur',
    name: 'Amateur',
    icon: 'person',
    heroImage: '/images/categories/amateur.jpg',
    description: 'Discover the most popular community-uploaded content, real couples, and raw cuts.'
  },
  {
    id: 'milf',
    name: 'MILF',
    icon: 'family_restroom',
    heroImage: '/images/categories/milf.jpg',
    description: 'Sophisticated luxury series and experienced performers in high definition.'
  },
  {
    id: 'teen',
    name: 'Teen (18+)',
    icon: 'emergency',
    heroImage: '/images/categories/teen.jpg',
    description: 'Young adult performers and vibrant, energetic cinematic encounters (18+).'
  },
  {
    id: 'anal',
    name: 'Anal',
    icon: 'settings_input_component',
    heroImage: '/images/categories/anal.jpg',
    description: 'High-intensity, premium adult productions and uncensored releases.'
  },
  {
    id: 'lesbian',
    name: 'Lesbian',
    icon: 'female',
    heroImage: '/images/categories/lesbian.jpg',
    description: 'Passionate and aesthetic female-centered romance and encounters.'
  },
  {
    id: 'gay',
    name: 'Gay',
    icon: 'male',
    heroImage: '/images/categories/gay.jpg',
    description: 'Premium male-on-male productions, verified models, and exclusive releases.'
  },
  {
    id: 'transgender',
    name: 'Transgender / Shemale',
    icon: 'transgender',
    heroImage: '/images/categories/transgender.jpg',
    description: 'Stunning verified trans models, high-definition solo, and duo releases.'
  },
  {
    id: 'pov',
    name: 'POV',
    icon: 'visibility',
    heroImage: '/images/categories/pov.jpg',
    description: 'Immerse yourself completely. Experience every scene from the most intimate perspective.'
  },
  {
    id: 'big-tits',
    name: 'Big Tits',
    icon: 'bubble_chart',
    heroImage: '/images/categories/big-tits.jpg',
    description: 'Top busty models, natural and enhanced large chests in 4K resolution.'
  },
  {
    id: 'big-ass',
    name: 'Big Ass',
    icon: 'radio_button_checked',
    heroImage: '/images/categories/big-ass.jpg',
    description: 'Curvy performers, thick silhouettes, and booty-focused scenes.'
  },
  {
    id: 'blowjob',
    name: 'Blowjob & Oral',
    icon: 'record_voice_over',
    heroImage: '/images/categories/blowjob.jpg',
    description: 'Intense oral sex, deepthroat, facial, and POV oral encounters.'
  },
  {
    id: 'creampie',
    name: 'Creampie',
    icon: 'water_drop',
    heroImage: '/images/categories/creampie.jpg',
    description: 'Uncensored internal climaxes and intense passionate finishes.'
  },
  {
    id: 'threesome',
    name: 'Threesome & Groups',
    icon: 'groups',
    heroImage: '/images/categories/threesome.jpg',
    description: 'Dynamic group scenes, MFF, FFM, MMF, and wild party encounters.'
  },
  {
    id: 'interracial',
    name: 'Interracial',
    icon: 'diversity_1',
    heroImage: '/images/categories/interracial.jpg',
    description: 'Cross-cultural passion, BBC, and diverse international pairings.'
  },
  {
    id: 'ebony',
    name: 'Ebony',
    icon: 'dark_mode',
    heroImage: '/images/categories/ebony.jpg',
    description: 'Gorgeous dark-skinned models, curvy black performers, and solo shows.'
  },
  {
    id: 'latina',
    name: 'Latina',
    icon: 'wb_sunny',
    heroImage: '/images/categories/latina.jpg',
    description: 'Passionate Latin American performers, fiery scenes, and Brazilian beauties.'
  },
  {
    id: 'desi',
    name: 'Desi',
    icon: 'flare',
    heroImage: '/images/categories/desi.jpg',
    description: 'Authentic Indian, South Asian and Desi romance & cinematic films.'
  },
  {
    id: 'asian',
    name: 'Asian',
    icon: 'temple_buddhist',
    heroImage: '/images/categories/asian.jpg',
    description: 'Sensual Japanese, Korean, and East Asian high definition adult releases.'
  },
  {
    id: 'hentai',
    name: 'Hentai',
    icon: 'palette',
    heroImage: '/images/categories/hentai.jpg',
    description: '3D animated and high-energy uncensored anime adult features.'
  },
  {
    id: 'vr',
    name: 'VR (Virtual Reality)',
    icon: 'view_in_ar',
    heroImage: '/images/categories/vr.jpg',
    description: '180° and 360° fully immersive virtual reality adult experiences.'
  },
  {
    id: 'hardcore',
    name: 'Hardcore',
    icon: 'flash_on',
    heroImage: '/images/categories/hardcore.jpg',
    description: 'High-energy rough encounters, intense pounding, and uncensored releases.'
  },
  {
    id: 'fetish',
    name: 'Fetish & BDSM',
    icon: 'lock',
    heroImage: '/images/categories/fetish.jpg',
    description: 'Leather, latex, stockings, dominance, submission, and niche fantasies.'
  },
  {
    id: 'masturbation',
    name: 'Masturbation & Solo',
    icon: 'fingerprint',
    heroImage: '/images/categories/masturbation.jpg',
    description: 'Intimate solo performers, toy play, orgasms, and webcam recordings.'
  },
  {
    id: 'public',
    name: 'Public & Outdoor',
    icon: 'nature_people',
    heroImage: '/images/categories/public.jpg',
    description: 'Thrilling outdoor encounters, risky public spots, and flashing moments.'
  },
  {
    id: 'mature',
    name: 'Mature & Vintage',
    icon: 'auto_awesome',
    heroImage: '/images/categories/mature.jpg',
    description: 'Classic adult cinema, vintage retro gems, and mature senior performers.'
  }
];

import curatedDataset from './data/pornhubCurated.json';

// Preserves authentic metadata (views, likes, ratings) from curated dataset
export const VIDEOS: Video[] = ((curatedDataset as any) || []) as Video[];

export const BRAZZERS_VIDEOS: Video[] = [
  {
    id: 'bz-820285',
    title: 'Brazzers Exclusive Premiere - HD 4K Scene',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'Exclusive', 'HD', 'Trending', '4K', 'Premiere'],
    performers: ['Brazzers VIP Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=820285&ata=Navifapx',
    adLinkUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=820285&ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/820285/1118165/1118165_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/820285/1118165/1118165_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/820285/1118165/1118165_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/820285/1118165/1118165_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.4M',
    viewsCount: 2420000,
    rating: '99%',
    timeAgo: 'Just now',
    createdAt: new Date(Date.now() + 50000).toISOString(),
    description: 'Official Brazzers VIP exclusive release in crystal clear 4K definition.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 145000,
  },
  {
    id: 'bz-819910',
    title: 'Brazzers Ultra HD Spotlight Feature',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'Spotlight', '4K', 'HD', 'VIP'],
    performers: ['Brazzers Cast'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=819910&ata=Navifapx',
    adLinkUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=819910&ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/819910/1115346/1115346_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/819910/1115346/1115346_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/819910/1115346/1115346_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/819910/1115346/1115346_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '1.8M',
    viewsCount: 1820000,
    rating: '98%',
    timeAgo: '1 day ago',
    createdAt: new Date(Date.now() + 40000).toISOString(),
    description: 'High definition Brazzers spotlight performance in 4K resolution.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 98000,
  },
  {
    id: 'bz-818621',
    title: 'Brazzers Exclusive Passion Series - 4K Release',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Passion', 'HD', '4K', 'Exclusive'],
    performers: ['Brazzers Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=818621&ata=Navifapx',
    adLinkUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=818621&ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/818621/1096046/1096046_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/818621/1096046/1096046_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/818621/1096046/1096046_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/818621/1096046/1096046_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.1M',
    viewsCount: 2100000,
    rating: '97%',
    timeAgo: '2 days ago',
    createdAt: new Date(Date.now() + 30000).toISOString(),
    description: 'Uncensored high definition scene from Brazzers Network.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 112000,
  },
  {
    id: 'bz-817592',
    title: 'Brazzers VIP Premium Performance - Full HD',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'VIP', 'Full HD', 'Trending'],
    performers: ['Brazzers Cast'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=817592&ata=Navifapx',
    adLinkUrl: 'https://landing1.brazzersnetwork.com/tgp1?ad_id=817592&ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/817592/1083548/1083548_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/817592/1083548/1083548_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/817592/1083548/1083548_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/817592/1083548/1083548_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '1.5M',
    viewsCount: 1540000,
    rating: '99%',
    timeAgo: '3 days ago',
    createdAt: new Date(Date.now() + 20000).toISOString(),
    description: 'Brazzers VIP showcase in full 4K definition.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 89000,
  },
  {
    id: 'bz-812498',
    title: 'Brazzers Network Hall of Fame Blockbuster',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Blockbuster', '4K', 'Iconic', 'VIP'],
    performers: ['Brazzers Elite'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033958/1033958_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033958/1033958_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033958/1033958_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033958/1033958_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '3.2M',
    viewsCount: 3200000,
    rating: '99%',
    timeAgo: '4 days ago',
    createdAt: new Date(Date.now() + 10000).toISOString(),
    description: 'Top-tier Brazzers blockbuster scene.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 210000,
  },
  {
    id: 'bz-999141',
    title: 'Brazzers VIP Premier - 4K High Definition Scene',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'Premier', '4K', 'VIP', 'Exclusive'],
    performers: ['Brazzers VIP Cast'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999141/999141_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999141/999141_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999141/999141_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999141/999141_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.8M',
    viewsCount: 2800000,
    rating: '99%',
    timeAgo: '5 days ago',
    createdAt: new Date(Date.now() + 9000).toISOString(),
    description: 'Official Brazzers VIP premier release.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 180000,
  },
  {
    id: 'bz-999088',
    title: 'Brazzers Exclusive Passion Showcase - HD',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Passion', 'HD', 'Showcase'],
    performers: ['Brazzers Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999088/999088_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999088/999088_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999088/999088_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/999088/999088_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '1.9M',
    viewsCount: 1900000,
    rating: '98%',
    timeAgo: '6 days ago',
    createdAt: new Date(Date.now() + 8000).toISOString(),
    description: 'Intense passion performance on Brazzers Network.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 95000,
  },
  {
    id: 'bz-1033957',
    title: 'Brazzers All-Star Ultra HD Network Stream',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'All-Star', '4K', 'Ultra HD'],
    performers: ['Brazzers All-Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033957/1033957_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033957/1033957_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033957/1033957_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033957/1033957_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.5M',
    viewsCount: 2500000,
    rating: '99%',
    timeAgo: '1 week ago',
    createdAt: new Date(Date.now() + 7000).toISOString(),
    description: 'High octane all-star scene from Brazzers Network.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 160000,
  },
  {
    id: 'bz-1033956',
    title: 'Brazzers Uncensored VIP Cinema - 4K Release',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'VIP Cinema', '4K', 'Uncensored'],
    performers: ['Brazzers Top Models'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033956/1033956_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033956/1033956_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033956/1033956_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1033956/1033956_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.3M',
    viewsCount: 2300000,
    rating: '97%',
    timeAgo: '1 week ago',
    createdAt: new Date(Date.now() + 6000).toISOString(),
    description: 'Uncensored 4K feature cinema from Brazzers.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 140000,
  },
  {
    id: 'bz-1028572',
    title: 'Brazzers Iconic Stars Special Feature - 4K UHD',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'Iconic', '4K UHD', 'VIP'],
    performers: ['Brazzers Cast'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1028572/1028572_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1028572/1028572_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1028572/1028572_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1028572/1028572_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.7M',
    viewsCount: 2700000,
    rating: '99%',
    timeAgo: '1 week ago',
    createdAt: new Date(Date.now() + 5000).toISOString(),
    description: 'Iconic stars special feature by Brazzers.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 175000,
  },
  {
    id: 'bz-1027394',
    title: 'Brazzers Platinum Edition - Full Length 4K',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Platinum', '4K', 'Full Length'],
    performers: ['Brazzers Elite'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027394/1027394_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027394/1027394_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027394/1027394_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027394/1027394_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '2.1M',
    viewsCount: 2100000,
    rating: '98%',
    timeAgo: '2 weeks ago',
    createdAt: new Date(Date.now() + 4000).toISOString(),
    description: 'Platinum edition 4K scene from Brazzers Network.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 130000,
  },
  {
    id: 'bz-1027392',
    title: 'Brazzers Seduction Series - VIP HD Video',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Seduction', 'VIP', 'HD'],
    performers: ['Brazzers Cast'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027392/1027392_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027392/1027392_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027392/1027392_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1027392/1027392_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '1.7M',
    viewsCount: 1700000,
    rating: '97%',
    timeAgo: '2 weeks ago',
    createdAt: new Date(Date.now() + 3000).toISOString(),
    description: 'Sensual seduction series scene.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 88000,
  },
  {
    id: 'bz-1026620',
    title: 'Brazzers Gold Collection - Ultra HD Masterpiece',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'hardcore', 'exclusive'],
    tags: ['Brazzers', 'Gold Collection', '4K', 'Ultra HD'],
    performers: ['Brazzers VIP Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1026620/1026620_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1026620/1026620_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1026620/1026620_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1026620/1026620_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '3.1M',
    viewsCount: 3100000,
    rating: '99%',
    timeAgo: '2 weeks ago',
    createdAt: new Date(Date.now() + 2000).toISOString(),
    description: 'Gold collection masterpiece in 4K.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 195000,
  },
  {
    id: 'bz-1022041',
    title: 'Brazzers Diamond Edition - 4K Signature Scene',
    category: 'trending',
    categoryLabel: 'Trending',
    categories: ['trending', 'exclusive'],
    tags: ['Brazzers', 'Diamond Edition', '4K', 'Signature'],
    performers: ['Brazzers Elite Stars'],
    performerName: 'Brazzers Official',
    channelName: 'Brazzers',
    sourceWebsite: 'Brazzers Network',
    sourceWebsiteUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    adLinkUrl: 'https://www.brazzersnetwork.com/home/?ata=Navifapx',
    thumbnail: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1022041/1022041_video.mp4#t=0.001',
    thumbnailUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1022041/1022041_video.mp4#t=0.001',
    previewMp4Url: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1022041/1022041_video.mp4',
    embedUrl: 'https://hw-cdn2.contentabc.com/a7/creatives/1/49/812498/1022041/1022041_video.mp4',
    duration: '00:30',
    quality: '4K',
    views: '3.4M',
    viewsCount: 3400000,
    rating: '99%',
    timeAgo: '3 weeks ago',
    createdAt: new Date(Date.now() + 1000).toISOString(),
    description: 'Signature Diamond Edition 4K release on Brazzers.',
    isExclusive: true,
    isNew: true,
    isOriginal: true,
    likesCount: 220000,
  }
];

export const INITIAL_VIDEOS: Video[] = VIDEOS;

export const INITIAL_LANDING_BANNERS: import('./types').LandingBanner[] = [];


